### ISSUE TITLE
Changing the email content.

### ISSUE THREAD

**Issue by mehapps** [DenBeke/mailbear#2]
Hello,
I'm using the example form. An idea I had is to allow changing the email content, I changed it in mailbear.go but it seems to be the same still. Here is the mailbear.go file and the email content. Is there any way to be able to change it or am I doing something wrong? Thanks!

![image](https://github.com/DenBeke/mailbear/assets/63882957/e8b68ef2-2c7e-45a1-ada2-ae68cdd35bb6)
![image](https://github.com/DenBeke/mailbear/assets/63882957/adf4c492-b3d9-4f6a-9aa1-d84d083d69f0)

**Comment by DenBeke** [comment]
How are you running your updated code?

**Comment by mehapps** [comment]
> How are you running your updated code?

I used docker-compose to bring the docker container down and then back up. Is there a different way I should be doing it? I don't have much experience with Go. Thanks!

**Comment by DenBeke** [comment]
Go is a compiled language. So in order for changes in the .go files to have effect you need to build the executable/image again.

If you don't want to bother setting up Go, you can uncomment the build line in my `docker-compose.yml`: https://github.com/DenBeke/mailbear/blob/master/docker-compose.yml#L6 and comment the image line. That way it will rebuild everything for you.

**Comment by mehapps** [comment]
Awesome, thank you!

**Comment by EugeneDae** [comment]
Sorry for a dumb question, but how do I find the relevant .go file inside the Docker container to make those changes? I would also like to customize email content and subject, and I'm also using Docker Compose.

What I've tried:
```
docker exec -it mailbear /bin/sh
find . -name "*.go"
(nothing found)
```

**Comment by DenBeke** [comment]
As per my comment above, the Go files are not in the Docker container, only the compiled binary.
So if you want to change it, you'd need to do it locally (in this file: https://github.com/DenBeke/mailbear/blob/master/mailbear.go#L54) and then build the Docker image again.

**Comment by EugeneDae** [comment]
> As per my comment above, the Go files are not in the Docker container, only the compiled binary. So if you want to change it, you'd need to do it locally (in this file: https://github.com/DenBeke/mailbear/blob/master/mailbear.go#L54) and then build the Docker image again.

Now it clicked on me, thanks a lot! I was able to build a new Docker image with those changes. Happy New Year!
