### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by matthewshammond** [DenBeke/mailbear#3]
First and foremost, this project is great and exactly what I have been looking for to avoid paying a service provider. 

This isn't an issue as much as just a question. How do I redirect after the form has been submitted? After the form on my page has been submitted I am sent to the form url where it shows `{"message":"form was submitted successfully"}` 

I'd like after the form is submitted to be redirected back to the homepage.

**Comment by DenBeke** [comment]
You shouldn't just redirect/post to the forms backend, but do it with an Ajax call so that you stay on the same page.
I have some examples in the readme.

Or what are you trying to achieve?

**Comment by matthewshammond** [comment]
Definitely not an issue with the project as much as my lack of knowledge on implementation. Thank you.
